github:
  gitHubRawContentHost:                   'https://raw.githubusercontent.com'
  gitHubContentBranch:                    'feature/create-github-repo'
  gitHubSourceOwner:                      'Fiserv'
  gitHubUser:                             'username'
  gitHubAuthToken:                        'yourToken'
mongdb:
  db:                                     ''
  url:                                    ''
  user:                                   ''
  password:                               ''