github:
  gitHubRawContentHost:                   'https://raw.githubusercontent.com'
  gitHubContentBranch:                    'feature/create-github-repo'
  gitHubSourceOwner:                      'Fiserv'
  gitHubUser:                             'username'
  gitHubAuthTokenEnvVar:                  'GITHUB_AUTH_TOKEN'
  gitHubOrgsAPI:                          'https://api.github.com/orgs/Fiserv/'
  gitHubOrgsTeamsAPI:                     'https://api.github.com/orgs/Fiserv/teams'
  gitHubReposAPI:                         'https://api.github.com/repos/Fiserv/'
  gitHubTemplateRepoAPI:                  'https://api.github.com/repos/Fiserv/sample-tenant-repo/generate'
  gitHubDevHook:                          'https://dev-developer.fiserv.com/api/github-push'
  gitHubDevHookKey:                       'secret123'
  gitHubQAHook:                           'https://qa-developer.fiserv.com/api/github-push'
  gitHubQAHookKey:                        'secret123'
  gitHubStageHook:                        'https://stage-developer.fiserv.com/api/github-push'
  gitHubStageHookKey:                     'secret123'
  gitHubProdHook:                         'https://developer.fiserv.com/api/github-push'
  gitHubProdHookKey:                      'secret123'
mongdb:
  db:                                     ''
  url:                                    ''
  user:                                   ''
  password:                               ''