github:
  gitHubRawContentHost:                   'https://raw.githubusercontent.com'
  gitHubContentBranch:                    'feature/create-github-repo'
  gitHubSourceOwner:                      'Fiserv'
  gitHubUser:                             'username'
  gitHubAuthToken:                        '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'
  gitHubAPI:                              'https://api.github.com/orgs/Fiserv/'
  gitHubAPIUrl:                           'https://api.github.com/orgs/Fiserv/teams'
  gitHubAPIRepo:                          'https://api.github.com/repos/Fiserv/'
  gitHubTemplateRepo:                     'https://api.github.com/repos/Fiserv/sample-tenant-repo/generate'
  gitHubDevHook:                          'https://dev-developer.fiserv.com/api/github-push'
  gitHubDevHookKey:                       'secret123'  
  gitHubQAHook:                           'https://qa-developer.fiserv.com/api/github-push'
  gitHubQAHookKey:                        'secret123' 
  gitHubStageHook:                        'https://stage-developer.fiserv.com/api/github-push'
  gitHubStageHookKey:                     'secret123' 
  gitHubProdHook:                         'https://developer.fiserv.com/api/github-push'
  gitHubProdHookKey:                      'secret123'       
mongdb:
  db:                                     ''
  url:                                    ''
  user:                                   ''
  password:                               ''